### ISSUE TITLE
Running example script fails with smbus2 "Remote I/O error"

### ISSUE THREAD

**Issue by stefan-girlich** [kyletaylored/tsl2591#3]
**python-tsl2591 version:**
0.2.0

**Python version:**
Python 3.5.3

**Operating System:**
Raspbian 9, _2019-04-08-raspbian-stretch-lite_

**Board:**
Raspberry Pi Zero W

### Description
I am trying to run the example script as suggested in in [Quickstart](https://github.com/kyletaylored/python-tsl2591#quickstart), but it fails with a generic error message.

### What I Did
1. Connect TSL2591 sensor as seen [here](https://github.com/LeivoSepp/Lesson-LightSensor-TSL2591#how-to-connect-this-sensor-into-raspberry-pi).
2. Successfully checked sensor connectivity: 
```
pi@pi-zero:~/luminosity-sensor $ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- 29 -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```
3. Run example script as default user _pi_ and _root, i. e. `python3 main.py` or `sudo python3 main.py`
4. In any case, the following error message appears: 
```
pi@pi-zero:~/luminosity-sensor $ sudo python3 main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    tsl = tsl2591()  # initialize
  File "/usr/local/lib/python3.5/dist-packages/python_tsl2591/sensor.py", line 102, in __init__
    self.set_timing(self.integration_time)
  File "/usr/local/lib/python3.5/dist-packages/python_tsl2591/sensor.py", line 107, in set_timing
    self.enable()
  File "/usr/local/lib/python3.5/dist-packages/python_tsl2591/sensor.py", line 175, in enable
    ENABLE_POWERON | ENABLE_AEN | ENABLE_AIEN
  File "/usr/local/lib/python3.5/dist-packages/smbus2/smbus2.py", line 391, in write_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
```

I understand this is an OS-level error unrelated to your library which can also be reproduced by using command-line tools. However, maybe you have experiences with this error and/or my particular setup. Thanks!

**Comment by stefan-girlich** [comment]
I was able to resolve my original issue by using a different set of cables.
